### ISSUE TITLE
add chat

### ISSUE THREAD

**Issue by lgg** [A-gambit/awesome-telegram-chats#72]
https://t.me/weblive - чат для веб разработчиков в телеграмме

Обсуждается:

- Frontend
- Backend
- CMS/CMF

Делятся опытом, помогают товарищам.

via https://toster.ru/q/269255?e=5831958#answer_item_1104724

**Comment by A-gambit** [comment]
@lgg pull request is welcome :)

**Comment by lgg** [comment]
- [x] add link above
- [x] personal links
- [x] parse https://github.com/mr-mig/ru-tech-chats

**Comment by lgg** [comment]
will fix this in bigger update, which is relative to #73 and #33
